### ISSUE TITLE
Wireframe - Color Pallet

### ISSUE THREAD

**Issue by stevevillardi** [stevevillardi/project1-pokepedia#10]
Start looking up bootswatch themes for possible color pallets for base css

**Comment by ThkPsss** [comment]
https://coolors.co/c3f73a-95e06c-68b684-094d92-1c1018 

^^^^^^^
Good Website for colors

**Comment by stevevillardi** [comment]
Was thinking about using this bootstrap style as a starting point and we can add in our own colors based on the pokemon color pallet:

https://bootswatch.com/lux/
